# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            WMT23 Terminology Shared Task
#tagline:          'A Jekyll theme'
description:      'Machine translation systems will be evaluated on their ability to translate specialized terminology accurately and consistently.'
#url:              http://hyde.getpoole.com
baseurl:          /

#author:
#  name:           'Mark Otto'
#  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2022

github:
  repo:           https://github.com/WMT-Metrics-task/
